ITIPD/ITIPD/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ITIPD.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('extractor.urls', namespace="documentationunit")),
)

ITIPD/extractor/urls.py
__author__ = 'sven'
from django.conf.urls import patterns, url
from extractor.models import DocumentationUnit, MappingUnitToUser
from extractor import views

urlpatterns = patterns('',
      url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
      url(r'^(?P<pk>\d+)/$', views.view_unit, name='detail'),
      url(r'^vote/$', views.vote, name='vote'),
      url(r'^parent/(?P<pk>\d+)/$', views.show_parent, name='parent'),
      url(r'^file/(?P<pk>\d+)/$', views.show_file, name='file'),
      url(r'^myunits/$', views.show_next_unit, name='show_next'),
      url(r'^markedunits/$', views.marked_units, name='marked_units'),
      url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/pydoc/login'}),
      url(r'^randomunit/$', views.random_mapping, name = 'random_mapping'),
      url(r'^mystats/$', views.mystats, name='mystats'),
      url(r'^compare_results/$', views.compare_results, name='compare_results'),
      url(r'^allstats/$', views.allstats, name='allstats'),
      url(r'^first_next/$', views.first_next, name='first_next'),
      url(r'agreement/(?P<pk>\d+)/$', views.show_compatibility, name='compatibility'),
      url(r'', 'django.contrib.auth.views.login', name='login')
)

ITIPD/extractor/models.py
from django.db import models


class DocumentationUnit(models.Model):
    html_text = models.TextField(max_length=None)
    filename = models.CharField(max_length=500, default="None")
    length = models.IntegerField(default=0)
    offset = models.IntegerField(default=-1)
    parent_text = models.TextField(max_length=None, default="") #improve?
    file_text = models.TextField(max_length=None, default="") #improve?
    type = models.CharField(max_length=100, default="") #why not a model for its own?
    plaintext = models.TextField(max_length=None)


class KnowledgeType(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=None, default="")


class MarkedUnit(models.Model):
    user = models.ForeignKey('auth.User', null=True, blank=True) #why are null and blank true?
    documentation_unit = models.ForeignKey(DocumentationUnit)
    knowledge_type = models.IntegerField(default=0)  # should be ForeignKey #improve?
    html_text = models.TextField() #improve? #does this text differ from the original?
    range = models.TextField(max_length=500, default='')
    char_range = models.TextField(max_length=500, default='')
    timestamp = models.DateTimeField(default=0)


class MappingUnitToUser(models.Model):
    user = models.ForeignKey('auth.User', null=True, blank=True)
    documentation_unit = models.ForeignKey(DocumentationUnit)
    already_marked = models.BooleanField(default=False)
    last_change = models.DateTimeField(default=0)
    unmarked_chars = models.IntegerField(default=0)
    unmarked_percent = models.IntegerField(default=0)


class AccessLog(models.Model):
    user = models.ForeignKey('auth.User', null=True, blank=True)
    documentation_unit = models.ForeignKey(DocumentationUnit)
    timestamp = models.DateTimeField(default=0)
    filename = models.CharField(max_length=100, default='') #improve name ? filename to action?

class Agreement(models.Model):
    first = models.ForeignKey(MappingUnitToUser, related_name="first")
    second = models.ForeignKey(MappingUnitToUser, related_name="second")
    percentage_by_types = models.FloatField(default=0)
    percentage_by_chars = models.IntegerField(default=0)

class Compatibility(models.Model):
    one = models.ForeignKey(MappingUnitToUser, related_name="one", default=None)
    two = models.ForeignKey(MappingUnitToUser, related_name="two", default=None)
    compatible = models.IntegerField(default=0)
    non_compatible = models.IntegerField(default=0)
    percentage_compatible = models.FloatField(default=0)
    percentage_based_on_chars = models.FloatField(default=0)

class Confusions(models.Model):
    atype = models.ForeignKey(KnowledgeType, related_name="atype", default=None)
    btype = models.ForeignKey(KnowledgeType, related_name="btype", default=None)
    idofa = models.ForeignKey(MarkedUnit, related_name="idofa", default=0)
    idofb = models.ForeignKey(MarkedUnit, related_name="idofb", default=0)
    length = models.IntegerField(default=0)

ITIPD/extractor/templates/extractor/agreement.html
{% extends "base.html" %}

{% if error_message %}<p xmlns="http://www.w3.org/1999/html"><strong>{{ error_message }}</strong></p>{% endif %}

{% block title %}Agreement{% endblock %}
{% block head %}
    {% load static %}
{% endblock %}

{% block content %}
<h1>Compatible!</h1>
    Compatible: {{ compatible }} <br>
    Trues: {{ trues }} <br>
    Falses: {{ falses }}  <br>
    Total: {{ total }} <br>
    In Percent: {{ in_percent }}, <br>
    Trues in Char: {{ true_chars }}<br>
    False in Char: {{ false_chars }}<br>
    Check if is 100: {{ add_both }}<br>

{% endblock %}

ITIPD/extractor/templates/extractor/allstats.html
{% extends "base.html" %}

{% block title %}General Statistics{% endblock %}
{% block head %}{% endblock %}

{% block content %}
{% csrf_token %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<table border="0" class="center-table">
  <tr>
    <th>Description</th>
    <th>Number of elements</th>
  </tr>
  <tr>
    <td>saved units (including units without markings)</td>
    <td>{{total_marked_units}}</td>
  </tr>
  <tr>
    <td>marked units (only with at least 1 marking)</td>
    <td>{{all_distinct}}</td>
  </tr>
  <tr>
    <td>elements left</td>
    <td>{{total_unmarked_units}}</td>
  </tr>
  <tr>
    <td>in total</td>
    <td>{{total_units}}</td>
  </tr>
</table>


<table border="1" class="center-table">
  <tr>
    <th>Student</th>
    <th>saved elements</th>
    <th>in 14 days</th>
    <th>in 8 days</th>
    <th>in 4 days</th>
    <th>in 2 days</th>
  </tr>
  <tr>
  {% for key, value in units_per_student.items %}
      <td>{{key.username}} </td>
      {% for items in value %}
        <td>{{items}}</td>
      {% endfor %}
  </tr>
 {% endfor %}
</table>

<table border="1" class="center-table">
  <tr>
    <th>Student</th>
    <th>total agreement</th>
    <th>in 14 days</th>
    <th>in 8 days</th>
    <th>in 4 days</th>
    <th>in 2 days</th>
  </tr>
  <tr>
  {% for key, value in agreement_per_student.items %}
      <td>{{key.username}} </td>
      {% for items in value %}
        <td>{{items}}</td>
      {% endfor %}
  </tr>
 {% endfor %}
</table>

<table border="1" class="center-table">
  <tr>
    <th>Validator</th>
    <th>saved elements</th>
    <th>in 14 days</th>
    <th>in 8 days</th>
    <th>in 4 days</th>
    <th>in 2 days</th>

  </tr>
  <tr>
  {% for key, value in units_per_validator.items %}
      <td>{{key.username}} </td>
      {% for items in value %}
        <td>{{items}}</td>
      {% endfor %}
  </tr>
 {% endfor %}
</table>




{% endblock %}

ITIPD/extractor/templates/extractor/compare_results.html
{% extends "base.html" %}

{% block title %}General Statistics{% endblock %}
{% block head %}{% endblock %}

{% block content %}
{% csrf_token %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<table border="1" class="center-table">
  <tr>
    <th>saving</th>
    <th>unit(id)</th>
    <th>agreement</th>
    <th>compatibility in chars</th>
    <th>compatibility by type</th>
    <th>student1</th>
  </tr>
  <tr>
  {% for value in results %}
      <td>{{value.0}} </td>
      <td>{{value.1}} </td>
      <td>{{value.2}} </td>
      <td>{{value.3}} </td>
      <td>{{value.4}} </td>
      <td>{{value.5}} </td>
  </tr>
  {% endfor %}

</table>

{% endblock %}

ITIPD/extractor/templates/extractor/detail.html
{% extends "base.html" %}

{% if error_message %}<p xmlns="http://www.w3.org/1999/html"><strong>{{ error_message }}</strong></p>{% endif %}

{% block title %}Code this Documentation-Unit{% endblock %}
{% block head %}
    {% load static %}
    <script type="text/javascript" src="{% static 'extractor/main.js' %}"></script>
{% endblock %}

{% block content %}
    {% autoescape off %}
    <h1 id="documentationunitid" class="{{object.id}}">documentation unit: {{object.id}}</h1>
    <hr />
    <div id="objecttext">{{object.html_text}}</div>
    {% endautoescape %}
<script type="text/javascript">
    window.ranges_marked = [];
    var False = false;
    var True = true;

    {% for range in marked_units %}
        window.ranges_marked.push({
          "type": {{range.knowledge_type }},
          "serializedRange": "{{range.range }}",
          {% autoescape off %}
          "characterRange": {{range.char_range }}
          {% endautoescape %}
          });
    {% endfor %}


</script>
 <ul id="typemenu">
     <lh>Types</lh>
     <li id="1" class="functionalityandbehavior"><a href="#">Functionality and Behavior</a></li>
     <li id="2" class="concepts"><a href="#">Concepts</a></li>
     <li id="3" class="directives"><a href="#">Directives</a></li>
     <li id="4" class="purposes"><a href="#">Purpose and Rationale</a></li>
     <li id="5" class="qualityattributes"><a href="#">Quality Attributes and Internal Aspects</a></li>
     <li id="6" class="controlflow"><a href="#">Control-Flow</a></li>
     <li id="7" class="structure"><a href="#">Structure and Relationships</a></li>
     <li id="8" class="patterns"><a href="#">Patterns</a></li>
     <li id="9" class="codeexamples"><a href="#">Code Examples</a></li>
     <li id="10" class="environment"><a href="#">Environment</a></li>
     <li id="11" class="externalreferences"><a href="#">External References</a></li>
     <li id="12" class="noninformation"><a href="#">Non-Information</a></li>
  </ul>

    <hr />

     <button id="submitbutton">Save</button>
     <button id="deletebutton">Delete All</button>

     <a href="{% url 'documentationunit:parent' object.id %}">Show Parent</a>
     <a href="{% url 'documentationunit:file' object.id %}" target="_blank">Show File</a>

<ul id="sortable">
</ul>
{% endblock %}

ITIPD/extractor/templates/extractor/markedunits.html
{% extends "base.html" %}

{% block title %}Saved units{% endblock %}
{% block head %}{% endblock %}

{% block content %}
{% csrf_token %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
  <p><strong>This list contains every unit which was saved.. </strong></p>
  <p>Unfinished units are yellow highlighted</p>
<div id="unit-list">
   <ul>
    {% for unit in units %}
       {% if unit.unmarked_chars > 100 and unit.unmarked_percent > 25 %}
           <li><a href="/pydoc/{{ unit.documentation_unit.id }}/" class="unmarked">ID: {{unit.documentation_unit.id}}
            <strong>{{ unit.documentation_unit.filename }}</strong>
            - Type: {{ unit.documentation_unit.type }}
            - Unmarked: {{unit.unmarked_percent}} %
            - last save: {{ unit.last_change }}
            </a></li>
       {% else %}
           <li><a href="/pydoc/{{ unit.documentation_unit.id }}/">ID: {{unit.documentation_unit.id}}
            <strong>{{ unit.documentation_unit.filename }}</strong>
            - Type: {{ unit.documentation_unit.type }}
            - last save: {{ unit.last_change }}
            </a></li>
       {% endif %}
    {% endfor %}
   </ul>
</div>
{% endblock %}

ITIPD/extractor/templates/extractor/mystats.html
{% extends "base.html" %}

{% block title %}My Statistic{% endblock %}
{% block head %}{% endblock %}

{% block content %}
{% csrf_token %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<p> Hello {{user.first_name}} {{user.last_name}}, this page is all about you. </p>

<table border="0" class="center-table">
  <tr>
    <th>Description</th>
    <th>total elements</th>
    <th>last 14 days</th>
    <th>last 8 days</th>
    <th>last 4 days</th>
    <th>last 2 days</th>
  </tr>
  <tr>
    <td>Already saved elements</td>
    <td>{{total_marked_units}}</td>
    <td>{{marked_14}}</td>
    <td>{{marked_8}}</td>
    <td>{{marked_4}}</td>
    <td>{{marked_2}}</td>
  </tr>
  <tr>
    <td>elements left</td>
    <td>{{total_unmarked_units}}</td>
  </tr>
  <tr>
    <td>saved and unsaved</td>
    <td>{{total_units}}</td>
  </tr>
  <tr>
    <td>agreement in %</td>
    <td>{{agreement_total}}</td>
    <td>{{agreement_14}}</td>
    <td>{{agreement_8}}</td>
    <td>{{agreement_4}}</td>
    <td>{{agreement_2}}</td>
  </tr>
  <tr>
    <td>agreement based on </td>
    <td>{{agreement_total_count}} units</td>
    <td>{{agreement_14_count}} units</td>
    <td>{{agreement_8_count}} units</td>
    <td>{{agreement_4_count}} units</td>
    <td>{{agreement_2_count}} units</td>
  </tr>

</table>

<p>Keep in mind: The agreement per unit also changes if the saving of an other participant changes. </p>
<p>Please do not change your markings if you are pretty sure that these are correct. </p>

        
{% endblock %}

ITIPD/extractor/templates/extractor/next_units.html
{% extends "base.html" %}

{% block title %}Next units{% endblock %}
{% block head %}{% endblock %}

{% block content %}
{% csrf_token %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
  <p><strong>This list contains every unit which was not saved yet.</strong></p>
<div id="unit-list">
   <ul>
    {% for unit in units %}
       <li><a href="/pydoc/{{ unit.id }}/">ID: {{unit.id}}  <strong>{{ unit.filename }}</strong>Type: {{ unit.type }}</a></li>
    {% endfor %}
   </ul>
</div>
{% endblock %}

ITIPD/extractor/templates/extractor/no_units.html
{% extends "base.html" %}

{% block title %}No units for you.{% endblock %}
{% block head %}{% endblock %}

{% block content %}
    <h2>Sorry {{user.first_name}} {{user.last_name}}, there are <b> no </b> units for you.</h2>
    </br>
    Might be an error? Contact the responsible admin!
{% endblock %}

ITIPD/extractor/templates/extractor/parents.html
{% extends "base.html" %}

{% block title %}Parent of documentation unit{% endblock %}
{% block head %}{% endblock %}

{% block content %}
{% csrf_token %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% autoescape off %}
    <h2>This is the parent of documentation unit {{object.id}}</h2>
        <a href="javascript:history.back();">Back</a>
        <hr />
            <div id="objecttext">{{object.parent_text}}</div>
{% endautoescape %}

 <hr />
 <a href="{% url 'documentationunit:detail' object.id %}">Show Unit</a>
{% endblock %}

ITIPD/extractor/templates/extractor/randomunit.html
{% extends "base.html" %}
{% block content %}

<p>You successfully mapped a random unit to your "MappedUnits".</p>
 
<p> <b> This is for testing and debugging only! </b> </p>
{% endblock %}